name: Release Build

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name (e.g. v1.2.3)'
        required: true
  push:
    tags:
      - 'v*'

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Determine version
        id: clean_version
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            # Автоматический запуск по тегу
            VERSION="${GITHUB_REF#refs/tags/v}"
            TAG_NAME="${GITHUB_REF#refs/tags/}"
          else
            # Ручной запуск — используем введённый тег
            TAG_NAME="${{ github.event.inputs.tag }}"
            VERSION="${TAG_NAME#v}"
          fi

          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT

      - name: Update version in header
        run: |
          sed -i "s|@version.*|@version      ${{ steps.clean_version.outputs.version }}|" tampermonkey-header.js

      - name: Build userscript
        run: npm run build

      - name: Upload artifact to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.clean_version.outputs.tag_name }}
          files: build/ficbook-export.user.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
