name: Trigger Release Build

on:
  issue_comment:
    types: [created]

jobs:
  trigger:
    if: contains(github.event.comment.body, 'autorelease: tagged')
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Release Build
        run: gh workflow run release-build.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
