name: Trigger Release Build

on:
  issues:
    types: [labeled]

jobs:
  trigger:
    if: "github.event.label.name == 'autorelease: tagged'"
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Release Build
        run: gh workflow run release-build.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
