name: Update Userscript

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  commit-userscript:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build userscript
        run: npm run build

      - name: Copy built userscript
        run: cp build/ficbook-export.user.js ficbook-export.user.js

      - name: Commit updated userscript
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add ficbook-export.user.js
          git commit -m "Update userscript" || echo "No changes to commit"
          git push
